the task filters have been included in a query object, but the query …
JoseCarlos-13/to-do-api pull request #11
Opened 2022-12-06 01:40 UTC by JoseCarlos-13

…task file spec still in development

2022-12-07 02:40 UTC, ricardobsilva requested changes

2022-12-07 02:40 UTC, ricardobsilva commented on spec/queries/task_filter_query_spec.rb
> +require 'support/request_helper_spec'
Esse helper serve somente para testes de request. Não é necessário importa-lo aqui

2022-12-07 02:40 UTC, ricardobsilva commented on app/queries/task_filter_query.rb
> +class TaskFilterQuery
Esse Filter no nome não me parece muito correto. A gente está fazendo queries em cima da entidade Task, então ' TasksQuery ' me parece fazer mais sentido, conforme o artigo que lemos sugere.

2022-12-07 02:40 UTC, ricardobsilva commented on app/queries/task_filter_query.rb
> +  def initialize(params)
Para não ficar chamando "Task" em todos os métodos, vc pode criar uma váriavel que guarde isso, ficando assim:

```
def initialize(params, task = Task)
    @params = params
    @task = task
  end

  def filter_by_status
    @task.where(status: @task.statuses[@params])
  end

  def filter_by_title
    @task.where('title like ?', "%#{@params}%")
  end

  def filter_by_user_name
    @task.joins(:user).where('name like ?', "%#{@params}%")
  end
```

2022-12-07 02:40 UTC, ricardobsilva commented on app/controllers/tasks_controller.rb
>        task_list = Task
Essa linha se torna irrelevante, pois Task será invocado dentro do QueryObject (ver comentário que deixei no task_filter_query.rb)

2022-12-07 02:40 UTC, ricardobsilva commented on app/queries/task_filter_query.rb
> +    Task.joins(:user).where('name like ?', "%#{@params}%")
O 'filter' tb pode ser removido dos metodos.  Basta começar a partir do by, assim:

def by_status

def by_title

def by_user_name

A leitura do metodo ja vai formar o significado "tasks by..", ex:

TaskQuery.new(@params).by_status

2022-12-07 17:08 UTC, JoseCarlos-13 commented on app/queries/task_filter_query.rb
> +  def initialize(params)
eu tinha feito isso, mas removi porque achei desnecessário.

2022-12-07 17:09 UTC, JoseCarlos-13 commented on spec/queries/task_filter_query_spec.rb
> +require 'support/request_helper_spec'
apenas esqueci de remover esses arquivos durante a formação da base dos testes

2022-12-11 03:54 UTC, ricardobsilva approved these changes

2022-12-11 03:54 UTC, ricardobsilva commented on app/controllers/tasks_controller.rb
> +    task_list = Task.all if task_list.empty?
essa linha se tornou desnecessaria, pq o query object ja vai retornar Task.all quando ele nao receber algum filtro

2022-12-11 03:54 UTC, ricardobsilva commented on spec/queries/tasks_query_spec.rb
> +        @query_response = TasksQuery.new(params).call
Response remete a request. Altera pra @tasks mesmo,  que é o que esse objeto vai guardar

2022-12-11 03:54 UTC, ricardobsilva commented on spec/queries/tasks_query_spec.rb
> +        @query_response = TasksQuery.new(params).call
Response remete a request. Altera pra @tasks mesmo,  que é o que esse objeto vai guardar

2022-12-11 03:54 UTC, ricardobsilva commented on spec/queries/tasks_query_spec.rb
> +        @query_response = TasksQuery.new(params).call
Response remete a request. Altera pra @tasks mesmo,  que é o que esse objeto vai guardar

2022-12-12 02:45 UTC, ricardobsilva approved these changes

2022-12-12 14:24 UTC, merged